import type { DashboardOverviewData } from "@/features/dashboard/types";

export const mockDashboardOverview: DashboardOverviewData = {
  organizationName: "Clinica Exemplo",
  periodLabel: "Hoje",
  metrics: [
    {
      label: "Total de conversas",
      value: "1.248",
      description: "Conversas registradas no ciclo atual.",
      trend: "+18% vs ciclo anterior",
      tone: "primary",
    },
    {
      label: "Total de clientes",
      value: "842",
      description: "Clientes e leads ativos na base.",
      trend: "+63 novos este mes",
      tone: "neutral",
    },
    {
      label: "Leads capturados",
      value: "126",
      description: "Novas oportunidades geradas por conversa.",
      trend: "32 qualificados",
      tone: "success",
    },
    {
      label: "Agendamentos do dia",
      value: "18",
      description: "Horarios solicitados, confirmados ou remarcados.",
      trend: "5 aguardando confirmacao",
      tone: "primary",
    },
    {
      label: "Pagamentos pendentes",
      value: "R$ 8.420",
      description: "Valor em cobrancas abertas e vencidas.",
      trend: "11 clientes pendentes",
      tone: "warning",
    },
    {
      label: "Precisam de humano",
      value: "9",
      description: "Conversas em handoff ou com risco comercial.",
      trend: "3 urgentes",
      tone: "danger",
    },
  ],
  messageVolume: [
    { day: "Segunda", shortLabel: "Seg", messages: 132 },
    { day: "Terca", shortLabel: "Ter", messages: 164 },
    { day: "Quarta", shortLabel: "Qua", messages: 148 },
    { day: "Quinta", shortLabel: "Qui", messages: 211 },
    { day: "Sexta", shortLabel: "Sex", messages: 246 },
    { day: "Sabado", shortLabel: "Sab", messages: 176 },
    { day: "Domingo", shortLabel: "Dom", messages: 97 },
  ],
  recentConversations: [
    {
      id: "conv_001",
      customerName: "Mariana Alves",
      channel: "WhatsApp",
      status: "Qualificacao",
      intent: "Agendar avaliacao",
      lastMessage: "Perguntou sobre horarios livres para esta semana.",
      lastActivity: "Ha 8 min",
      requiresHuman: false,
    },
    {
      id: "conv_002",
      customerName: "Roberto Lima",
      channel: "WhatsApp",
      status: "Handoff",
      intent: "Negociar proposta",
      lastMessage: "Pediu condicao especial antes de fechar.",
      lastActivity: "Ha 19 min",
      requiresHuman: true,
    },
    {
      id: "conv_003",
      customerName: "Claudia Mendes",
      channel: "WhatsApp",
      status: "Recuperacao",
      intent: "Retornar atendimento",
      lastMessage: "Cliente inativa respondeu campanha de retorno.",
      lastActivity: "Hoje, 10:42",
      requiresHuman: false,
    },
    {
      id: "conv_004",
      customerName: "Ana Paula",
      channel: "Manual",
      status: "Agenda",
      intent: "Confirmar horario",
      lastMessage: "Solicitou confirmacao para amanha de manha.",
      lastActivity: "Hoje, 09:16",
      requiresHuman: true,
    },
    {
      id: "conv_005",
      customerName: "Felipe Nogueira",
      channel: "Web",
      status: "Novo lead",
      intent: "Consultar servico",
      lastMessage: "Entrou pela pagina de precos e pediu detalhes.",
      lastActivity: "Ontem",
      requiresHuman: false,
    },
  ],
};
